name: 'Aider AI Assistant'

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  aider-resolver:
    # Only run on comments/issues that mention @agent
    if: contains(github.event.comment.body, '@agent') || contains(github.event.issue.body, '@agent')
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Run Aider AI Assistant
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # AI Provider API Keys (configure in repository secrets)
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
          
          # Configuration
          default_model: 'deepseek'  # Cost-effective default
          max_execution_time: '30'   # 30 minutes timeout
          enable_auto_pr: 'true'     # Automatically create PRs
          cost_budget_daily: '10'    # $10 daily budget
          
          # Optional: restrict to specific users
          # allowed_users: 'owner,maintainer,contributor'
          
          # Optional: custom config file location
          # config_file: '.github/agents.md'
      
      - name: Handle Results
        if: always()
        run: |
          echo "Operation completed with result: ${{ steps.aider.outputs.result }}"
          echo "Files changed: ${{ steps.aider.outputs.files_changed }}"
          echo "Cost used: ${{ steps.aider.outputs.cost_used }}"
          if [[ -n "${{ steps.aider.outputs.pull_request_url }}" ]]; then
            echo "Pull request created: ${{ steps.aider.outputs.pull_request_url }}"
          fi
